### ISSUE TITLE
cannot import name 'config' from 'finrl.apps' in Demo_MultiCrypto_Trading

### ISSUE THREAD

**Issue by Arstam** [AI4Finance-Foundation/FinRL-Meta#106]
There is a new issue in the colab notebook, any idea on how to fix it ?
![image](https://user-images.githubusercontent.com/50753999/158402759-353d7fe6-7247-41bd-8d01-04cae5e8a5e7.png)

**Comment by XiaoYangLiu-FinRL** [comment]
Pls check the new path… we recently made some change, still cleaning it.

**Comment by zhumingpassional** [comment]
please try from finrl import config. 
If you use tickers, try from finrl import config_tickers
