### ISSUE TITLE
'module' object is not callable in Demo_crypto

### ISSUE THREAD

**Issue by Arstam** [AI4Finance-Foundation/FinRL-Meta#107]
Hi ! I managed the previous issue by deleting it, just the time I found a solution, but now I have a new problem. Certainly not a lot but I don't know hwo to fix it
![image](https://user-images.githubusercontent.com/50753999/158410699-6c065795-a965-4014-b954-d97bd0521aa5.png)

**Comment by zhumingpassional** [comment]
Fixed.

Please use the newest version.
