### ISSUE TITLE
I really want to know that how to use the forex env? and what is the format of csv for forex training?

### ISSUE THREAD

**Issue by yiivon** [AI4Finance-Foundation/FinRL-Meta#123]
in other the word, i seeing the env_fx.py contains these two lines hard-code:
```
        self.df = df
        self.df["_time"] = df[self.time_col]
        self.df["_day"] = df["weekday"]
```
what is that means? 

Thank you very much if there be a reply, thanks again!

**Comment by rayrui312** [comment]
This env is merged from trading_gym. Data can be found here https://github.com/cove9988/TradingGym/tree/master/data. After downloading the data file to your local device, you can follow this notebook https://github.com/AI4Finance-Foundation/FinRL-Meta/blob/master/Demo_ForexTrading_Demo.ipynb.

**Comment by yiivon** [comment]
Thank you!
