### ISSUE TITLE
Error to run Demo Plug and Play notebook

### ISSUE THREAD

**Issue by montshasta2020** [AI4Finance-Foundation/FinRL-Meta#14]
KeyError                                  Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/finrl/drl_agents/elegantrl/models.py in get_model(self, model_name, model_kwargs)
     64                 model.net_dim = model_kwargs["net_dimension"]
---> 65                 model.target_step = model_kwargs["target_step"]
     66                 model.eval_gap = model_kwargs["eval_gap"]

KeyError: 'target_step'

**Comment by rayrui312** [comment]
Thanks for reporting it. Which notebook are you using?

**Comment by montshasta2020** [comment]
Demo_Plug_and_Play_with_DRL_Libraries.ipynb

**Comment by rayrui312** [comment]
The notebook is updated now. Thanks for reporting the error.
