### ISSUE TITLE
Corrupted file: China_A_share_market_tushare.ipynb

### ISSUE THREAD

**Issue by Yonv1943** [AI4Finance-Foundation/FinRL-Meta#166]
File `China_A_share_market_tushare.ipynb` is corrupted. It does not display properly on the web page. Can you upload a version that can be opened correctly?

See this corrupted ipynb file:
https://github.com/AI4Finance-Foundation/FinRL-Meta/blob/master/tutorials/1-Introduction/China_A_share_market_tushare/China_A_share_market_tushare.ipynb

**Comment by zhumingpassional** [comment]
fixed
