### ISSUE TITLE
Can not find the Demo_China_A_share_market.ipynb

### ISSUE THREAD

**Issue by tairen99** [AI4Finance-Foundation/FinRL-Meta#199]
Thank you for your good work.

For some reason, I could not find the link for "Demo_China_A_share_market.ipynb".

The full link was: https://github.com/AI4Finance-Foundation/FinRL-Meta/blob/master/Demo_China_A_share_market.ipynb

Can you please provide some hints?

Thank you.

**Comment by XiaoYangLiu-FinRL** [comment]
Are you looking for: https://github.com/AI4Finance-Foundation/FinRL-Meta/blob/master/tutorials/1-Introduction/China_A_share_market_tushare.ipynb

**Comment by tairen99** [comment]
Hi @XiaoYangLiu-FinRL,

Thank you for your reply.

I am looking for a Google Colab link that contains the work from Tongji University using the DDPG algorithm. 

It was available using the link: https://github.com/AI4Finance-Foundation/FinRL-Meta/blob/master/Demo_China_A_share_market.ipynb. 

It looks like the link you pointed to (https://github.com/AI4Finance-Foundation/FinRL-Meta/blob/master/tutorials/1-Introduction/China_A_share_market_tushare.ipynb), but when I click the Google Colab icon from your link, it gives me the error as below image:
![image](https://user-images.githubusercontent.com/32938376/179387098-48dc1abd-982d-4c7e-9dc0-52c9b8d52f61.png)

Please help.

Thank you again.

**Comment by tairen99** [comment]
Hi @kabua,

Thank you for your comment.

The link [https://github.com/AI4Finance-Foundation/FinRL-Meta/blob/master/tutorials/1-Introduction/China_A_share_market_tushare.ipynb)](url) is working now.

The  Google Colab also works. I guess @ZiyiXia fixed the corrupted link.
Thank you both of you!
