### ISSUE TITLE
Problems when using joinquant data?

### ISSUE THREAD

**Issue by Waterkin** [AI4Finance-Foundation/FinRL-Meta#20]
In Demo_Plug_and_Play_with_DRL_Libraries.ipynb

①No preprocessor to deal with inconsistent data, in config.SSE_50_ticker, the data is like '000001.SZ' but we get '000001.XSHE' from joinquant source. Thus, '找不到标的' error would occur.

②when train with joinquant data, error 'AttributeError: 'NoneType' object has no attribute 'copy'' arised. 
I assume that it happened because after function 'clean_data', the whole dataframe was cleaned to be empty.
So I look into the code and find that there was nothing about clean_data... So what happened?

③I strongly suggest a more complete doc about how to use FinRL-Meta, thanks.

![image](https://user-images.githubusercontent.com/41324537/143726882-7f0c37c6-b711-498e-ae3d-e9e2f176bb8e.png)

**Comment by zhumingpassional** [comment]
1 We noticed it. SZ should be changed to XSHE, and SS should be changed to XSHG. 
2 We will check it.
3 Thanks for your suggestions.

**Comment by Waterkin** [comment]
> 

Thanks for your reply, zhuming.

**Comment by zhumingpassional** [comment]
With respect to joinquant, if the interval is 1 day, do not use clean_data function. clean_data is generally used in low intervals, e.g. 1 minute.
