### ISSUE TITLE
Missing doc strings

### ISSUE THREAD

**Issue by eyast** [AI4Finance-Foundation/FinRL-Meta#200]
Functions have missing doc strings,

**Comment by XiaoYangLiu-FinRL** [comment]
This issue seems not clear.

**Comment by eyast** [comment]
Why is this closed please ?
________________________________

**Comment by XiaoYangLiu-FinRL** [comment]
Could you please explain "Missing doc strings"?  I was not able to understand, thought it is not a serious issue and no one joined....
If you think it is important, let us re-open it, and I can invite members to fix it with you.

**Comment by eyast** [comment]
We need to add costrings to all the functions :)
________________________________
