### ISSUE TITLE
Turorial - Bad collab notbook formatting

### ISSUE THREAD

**Issue by kabua** [AI4Finance-Foundation/FinRL-Meta#209]
It appears the collab file somehow got corrupted in [Quantitative trading in China A stock market with FinRL](https://github.com/AI4Finance-Foundation/FinRL-Meta/blob/master/tutorials/1-Introduction/China_A_share_market_tushare.ipynb)

**Comment by zhumingpassional** [comment]
pls use the python version, which seems better.

**Comment by ZiyiXia** [comment]
The link was fixed.

**Comment by zhumingpassional** [comment]
@kabua  could you pls paste the raised errors?

**Comment by zhumingpassional** [comment]
https://github.com/AI4Finance-Foundation/FinRL/blob/master/tutorials/2-Advance/FinRL_Ensemble_StockTrading_ICAIF_2020.ipynb

**Comment by XiaoYangLiu-FinRL** [comment]
> I'm also having a problem authenticating with GitHub so that Colab can accessGitHubb. I've filled a bug with GitHub just now.

Another way is "download the file, Then upload it to Google colab".
