### ISSUE TITLE
Tutorials - missing link

### ISSUE THREAD

**Issue by kabua** [AI4Finance-Foundation/FinRL-Meta#210]
In [Deep Reinforcement Learning for Stock Trading from Scratch: Portfolio Allocation](https://colab.research.google.com/github/AI4Finance-Foundation/FinRL-Meta/blob/master/tutorials/1-Introduction/FinRL_PortfolioAllocation_NeurIPS_2020.ipynb)

The header states
```
Check out medium blog for detailed explanations:
```

But the link to this blog is missing.

**Comment by ZiyiXia** [comment]
The blog is: https://towardsdatascience.com/finrl-for-quantitative-finance-tutorial-for-portfolio-allocation-9b417660c7cd

The notebook has been updated, the link to medium blog is added. Thanks for pointing that out.
