### ISSUE TITLE
MultiCrypto_Trading  assert 

### ISSUE THREAD

**Issue by guo-li-hua** [AI4Finance-Foundation/FinRL-Meta#248]
run MultiCrypto_Trading and assert,    CPU model
TICKER_LIST = ['BTC-USD', 'ETH-USD']
train data source is 'yahoofinance'

![image](https://user-images.githubusercontent.com/34728163/201818920-738cb1be-11b2-4adb-a5fd-0838688ea8f5.png)

![image](https://user-images.githubusercontent.com/34728163/201819185-796563a7-4c8b-4eca-925e-ab20f2005b8a.png)

**Comment by zhumingpassional** [comment]
yahoofinance does not support crytocurrencies. pls choose other data processors such as binance, and alpaca
