### ISSUE TITLE
FinRL_MultiCrypto_Trading.ipynb ValueError: If using all scalar values, you must pass an index

### ISSUE THREAD

**Issue by aevfly** [AI4Finance-Foundation/FinRL-Meta#263]
Using FinRL_MultiCrypto_Trading.ipynb
https://colab.research.google.com/drive/15ttwd6OO5vBoUmibHzIjDlDZlIIG9MyG

in section Training 

train(start_date=TRAIN_START_DATE, 
      end_date=TRAIN_END_DATE,
      ticker_list=TICKER_LIST, 
      data_source='binance',
      time_interval='30m', 
      technical_indicator_list=INDICATORS,
      drl_lib='elegantrl', 
      env=env, 
      model_name='ppo', 
      current_working_dir='./test_ppo',
      erl_params=ERL_PARAMS,
      break_step=5e4,
      if_vix=False
      )

got this: ValueError: If using all scalar values, you must pass an index

full log:
-------------------------------
binance successfully connected
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-7-644186a21769>](https://localhost:8080/#) in <module>
----> 1 train(start_date=TRAIN_START_DATE, 
      2       end_date=TRAIN_END_DATE,
      3       ticker_list=TICKER_LIST,
      4       data_source='binance',
      5       time_interval='30m',

9 frames
[<ipython-input-3-c2f4f1f1ce9a>](https://localhost:8080/#) in train(start_date, end_date, ticker_list, data_source, time_interval, technical_indicator_list, drl_lib, env, model_name, if_vix, **kwargs)
     10     #process data using unified data processor
     11     DP = DataProcessor(data_source, start_date, end_date, time_interval, **kwargs)
---> 12     price_array, tech_array, turbulence_array = DP.run(ticker_list,
     13                                                         technical_indicator_list,
     14                                                         if_vix, cache=True)

[/FinRL-Meta/meta/data_processor.py](https://localhost:8080/#) in run(self, ticker_list, technical_indicator_list, if_vix, cache, select_stockstats_talib)
    182                 self.processor.dataframe = pickle.load(handle)
    183         else:
--> 184             self.download_data(ticker_list)
    185             self.clean_data()
    186             if cache:

[/FinRL-Meta/meta/data_processor.py](https://localhost:8080/#) in download_data(self, ticker_list)
    101 
    102     def download_data(self, ticker_list):
--> 103         self.processor.download_data(ticker_list=ticker_list)
    104         self.dataframe = self.processor.dataframe
    105 

[/FinRL-Meta/meta/data_processors/binance.py](https://localhost:8080/#) in download_data(self, ticker_list)
     61             final_df = pd.DataFrame()
     62             for i in ticker_list:
---> 63                 hist_data = self.dataframe_with_limit(symbol=i)
     64                 df = hist_data.iloc[:-1].dropna()
     65                 df["tic"] = i

[/FinRL-Meta/meta/data_processors/binance.py](https://localhost:8080/#) in dataframe_with_limit(self, symbol)
    191         while True:
    192 
--> 193             new_df = self.get_binance_bars(last_datetime, symbol)
    194             if new_df is None:
    195                 break

[/FinRL-Meta/meta/data_processors/binance.py](https://localhost:8080/#) in get_binance_bars(self, last_datetime, symbol)
    129         # r = requests.get(self.url, params=req_params)
    130         # print(r.text)
--> 131         df = pd.DataFrame(requests.get(self.url, params=req_params).json())
    132 
    133         if df.empty:

[/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py](https://localhost:8080/#) in __init__(self, data, index, columns, dtype, copy)
    612         elif isinstance(data, dict):
    613             # GH#38939 de facto copy defaults to False only in non-dict cases
--> 614             mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
    615         elif isinstance(data, ma.MaskedArray):
    616             import numpy.ma.mrecords as mrecords

[/usr/local/lib/python3.8/dist-packages/pandas/core/internals/construction.py](https://localhost:8080/#) in dict_to_mgr(data, index, columns, dtype, typ, copy)
    462         # TODO: can we get rid of the dt64tz special case above?
    463 
--> 464     return arrays_to_mgr(
    465         arrays, data_names, index, columns, dtype=dtype, typ=typ, consolidate=copy
    466     )

[/usr/local/lib/python3.8/dist-packages/pandas/core/internals/construction.py](https://localhost:8080/#) in arrays_to_mgr(arrays, arr_names, index, columns, dtype, verify_integrity, typ, consolidate)
    117         # figure out the index, if necessary
    118         if index is None:
--> 119             index = _extract_index(arrays)
    120         else:
    121             index = ensure_index(index)

[/usr/local/lib/python3.8/dist-packages/pandas/core/internals/construction.py](https://localhost:8080/#) in _extract_index(data)
    623 
    624         if not indexes and not raw_lengths:
--> 625             raise ValueError("If using all scalar values, you must pass an index")
    626 
    627         if have_series:

ValueError: If using all scalar values, you must pass an index

**Comment by xfocus3** [comment]
same error

**Comment by aevfly** [comment]
the problems that binance reject if request send from US servers, in this case response contain text message thats why I've got ValueError. 
Possible solution: 
1. send request from any other countries , non US servers 
2. or use another source to get data (alpaca, yahoo etc)
