### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'config'

### ISSUE THREAD

**Issue by uh-reza** [AI4Finance-Foundation/FinRL-Meta#28]
Hi, train RLlib come up with following error 

~/anaconda3/lib/python3.7/site-packages/ray/worker.py in get(object_refs, timeout)
   1625                     raise value.as_instanceof_cause()
   1626                 else:
-> 1627                     raise value
   1628 
   1629         if is_individual_id:

RayActorError: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=43634, ip=192.168.1.81)
AttributeError: 'NoneType' object has no attribute 'config'

During handling of the above exception, another exception occurred:

ray::RolloutWorker.__init__() (pid=43634, ip=192.168.1.81)
  File "/home/reza/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 565, in __init__
    devices = get_tf_gpu_devices()
  File "/home/reza/anaconda3/lib/python3.7/site-packages/ray/rllib/utils/tf_ops.py", line 54, in get_gpu_devices
    devices = tf.config.experimental.list_physical_devices()
AttributeError: 'NoneType' object has no attribute 'config'

it seems that is due to Tensorflow TensorBoard ... 
any idea, how can we sort it out? regards

**Comment by Athe-kunal** [comment]
I am not sure why it is using Tensorflow as the code is written on PyTorch. So try changing the 
`model_config['framework']='torch'`
I am not sure though

**Comment by zhumingpassional** [comment]
ElegantRL is developed using torch. Please use torch instead of tensorflow.

**Comment by uh-reza** [comment]
thank for the suggestions, 
I have installed FinRL-Meta on 20.04 as scratch, based on Demo_Plug_and_Play_with_DRL_Libraries.ipynb 

ubuntu 20.04
conda 4.8.2
python 3.7.6
pip 20.0.2

I don’t know what part of installation should be changed, any suggestion?

**Comment by Athe-kunal** [comment]
Before passing model_config to train_model, just do

`model_config['framework'] = 'torch'`

**Comment by uh-reza** [comment]
thank you, it worked fro Train (RLlib), but still problem is in Test (RLlib) with following error message, any advise? 

(pid=5609) 2021-12-06 13:42:38,359	ERROR worker.py:425 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=5609, ip=192.168.1.81)
(pid=5609) AttributeError: 'NoneType' object has no attribute 'config'
(pid=5609) 
(pid=5609) During handling of the above exception, another exception occurred:
(pid=5609) 
(pid=5609) ray::RolloutWorker.__init__() (pid=5609, ip=192.168.1.81)
(pid=5609)   File "/home/reza/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 565, in __init__
(pid=5609)     devices = get_tf_gpu_devices()
(pid=5609)   File "/home/reza/anaconda3/lib/python3.7/site-packages/ray/rllib/utils/tf_ops.py", line 54, in get_gpu_devices
(pid=5609)     devices = tf.config.experimental.list_physical_devices()
(pid=5609) AttributeError: 'NoneType' object has no attribute 'config'
(pid=5607) 2021-12-06 13:42:38,359	ERROR worker.py:425 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=5607, ip=192.168.1.81)
(pid=5607) AttributeError: 'NoneType' object has no attribute 'config'
(pid=5607) 
(pid=5607) During handling of the above exception, another exception occurred:
(pid=5607) 
(pid=5607) ray::RolloutWorker.__init__() (pid=5607, ip=192.168.1.81)
(pid=5607)   File "/home/reza/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 565, in __init__
(pid=5607)     devices = get_tf_gpu_devices()
(pid=5607)   File "/home/reza/anaconda3/lib/python3.7/site-packages/ray/rllib/utils/tf_ops.py", line 54, in get_gpu_devices
(pid=5607)     devices = tf.config.experimental.list_physical_devices()
(pid=5607) AttributeError: 'NoneType' object has no attribute 'config'

**Comment by Athe-kunal** [comment]
Similarly for test, I suppose

**Comment by uh-reza** [comment]
thank you, :)
