### ISSUE TITLE
I cannot understand your sharpe ratio in the ipynb.

### ISSUE THREAD

**Issue by cokemhlee** [AI4Finance-Foundation/FinRL-Meta#33]
Thanks for publishing a great framework.

As far as I know, Shape Ratio is usually defined as the difference between the returns of the investment and the risk-free return, divided by the standard deviation of the investment returns.

In the notebook 'FinRL_Ensemble_StockTrading_ICAIF_2020.ipynb', Part 7: Backtest Our Strategy,
You defined it as,
sharpe=(252**0.5)*df_account_value.account_value.pct_change(1).mean()/df_account_value.account_value.pct_change(1).std()

Could you please explain why?

**Comment by Athe-kunal** [comment]
Sharpe ratio is the ratio of [CAGR ](https://www.investopedia.com/terms/c/cagr.asp) and the standard deviation of the returns. 252 is the number of trading days in a year (including the weekends and holidays). Here the risk-free return is assumed to be 0.0, but you can include other risk-free returns as per your choice.

**Comment by cokemhlee** [comment]
Thanks for your kind reply.
