### ISSUE TITLE
Inconsistent datasource args in data_processor.py  and basic_processor

### ISSUE THREAD

**Issue by FredHJC** [AI4Finance-Foundation/FinRL-Meta#44]
<img width="943" alt="截屏2021-12-16 下午8 48 00" src="https://user-images.githubusercontent.com/24794992/146475291-e1b71572-72db-4275-aaea-725ec961863c.png">

<img width="1342" alt="截屏2021-12-16 下午8 48 24" src="https://user-images.githubusercontent.com/24794992/146475321-68939f62-84f6-4bad-9c3d-8e7b1d59e853.png">

The datasource for cryptos is named as binance. But in basic_processor, the code asserts if it is in a given list, in which it is called ccxt. This will throw an error

**Comment by rayrui312** [comment]
Thanks for reporting it. We have added "binance" to the list.
