### ISSUE TITLE
NameError: name 'MACD' is not defined

### ISSUE THREAD

**Issue by cryptocoinserver** [AI4Finance-Foundation/FinRL-Meta#45]
Demo_MultiCrypto_Trading.ipynb

```
Binance successfully connected
Adding self-defined technical indicators is NOT supported yet.
Use default: MACD, RSI, CCI, DX.

---------------------------------------------------------------------------

NameError                                 Traceback (most recent call last)

<ipython-input-15-29348b501caa> in <module>()
     11       erl_params=ERL_PARAMS,
     12       break_step=5e4,
---> 13       if_vix=False
     14       )

3 frames

/FinRL-Meta/finrl_meta/data_processors/processor_binance.py in add_technical_indicator(self, df, tech_indicator_list)
     48         for i in df.tic.unique():
     49             tic_df = df[df.tic==i]
---> 50             tic_df['macd'], tic_df['macd_signal'], tic_df['macd_hist'] = MACD(tic_df['close'], fastperiod=12, 
     51                                                                                 slowperiod=26, signalperiod=9)
     52             tic_df['rsi'] = RSI(tic_df['close'], timeperiod=14)

NameError: name 'MACD' is not defined
```

Caused by the commented line here:
[https://github.com/AI4Finance-Foundation/FinRL-Meta/blob/3a8fdcd7ad1e3ad8e3dbbc9a647cb5eef3769507/finrl_meta/data_processors/processor_binance.py#L6](https://github.com/AI4Finance-Foundation/FinRL-Meta/blob/3a8fdcd7ad1e3ad8e3dbbc9a647cb5eef3769507/finrl_meta/data_processors/processor_binance.py#L6)

**Comment by cryptocoinserver** [comment]
Also I'm not sure if this is the right place in general? Why not let the user take care of creating an indicator df, with indicators and the library of his choice and let him pass it via add_technical_indicator? Maybe even a more general add_features where he can pass a df with data?

**Comment by rayrui312** [comment]
1. Thanks for reporting errors. We have fixed it. 
2. We much appreciate your suggestions. Maybe we can add an option in the data processor for users to use our indicators or add by themselves. Would you like to share some specific ideas and discuss with us about the implementation? We will much appreciate a Pull Request from you.

**Comment by Athe-kunal** [comment]
Hi @cryptocoinserver, in this tutorial https://github.com/AI4Finance-Foundation/FinRL-Meta/blob/master/Demo_FinRL_Meta_Integrate_Trends_data_to_DOW_Jones.ipynb we tried to integrate custom user-defined features into the dataset. If you see in the Custom_DataProcessor class, there is a function called add_user_defined features. It is not very optimal, but a good place to start, I guess. Do provide some suggestions to improve it

**Comment by cryptocoinserver** [comment]
@Athe-kunal - I think this is exactly what I head in mind. I think this is sufficient and should be added by default? 
The issue seems to be fixed. So I will close it.
