### ISSUE TITLE
Opened "Demo_MultiCrypto_Trading.ipynb" in colab ran into multiple problems

### ISSUE THREAD

**Issue by amazingvince** [AI4Finance-Foundation/FinRL-Meta#58]
I was trying to run the multi crypto demo. I made a few changes to get through the first part maybe some of those need to be added. Happy to make a pull request if so. But still not able to get the demo to work.

pip install tushare is missing from install list

In the  "Functions for Training and Testing" block I had to add a directory change for it to find the data_processor
%cd /FinRL-Meta/
from drl_agents.elegantrl_models import DRLAgent as DRLAgent_erl
from drl_agents.rllib_models import DRLAgent as DRLAgent_rllib
from drl_agents.stablebaselines3_models import DRLAgent as DRLAgent_sb3
from finrl_meta.data_processor import DataProcessor

After these changes I was able to get to the training step but got stuck here with this error:
Binance successfully connected
Succesfully add technical indicators
| Arguments Remove cwd: ./test_ppo
################################################################################
ID     Step    maxR |    avgR   stdR   avgS  stdS |    expR   objC   etc.
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-12-29348b501caa> in <module>()
     11       erl_params=ERL_PARAMS,
     12       break_step=5e4,
---> 13       if_vix=False
     14       )

<ipython-input-7-ee68da53f50e> in train(start_date, end_date, ticker_list, data_source, time_interval, technical_indicator_list, drl_lib, env, model_name, if_vix, **kwargs)
     36         trained_model = agent.train_model(model=model, 
     37                                           cwd=current_working_dir,
---> 38                                           total_timesteps=break_step)
     39 
     40     elif drl_lib == 'rllib':

/FinRL-Meta/drl_agents/elegantrl_models.py in train_model(self, model, cwd, total_timesteps)
     79         model.cwd = cwd
     80         model.break_step = total_timesteps
---> 81         train_and_evaluate(args=model)
     82 
     83     @staticmethod

/usr/local/lib/python3.7/dist-packages/elegantrl/train/run.py in train_and_evaluate(***failed resolving arguments***)
     39 
     40         torch.set_grad_enabled(True)
---> 41         logging_tuple = agent.update_net(buffer, batch_size, repeat_times, soft_update_tau)
     42         torch.set_grad_enabled(False)
     43 

/usr/local/lib/python3.7/dist-packages/elegantrl/agents/AgentPPO.py in update_net(self, buffer, batch_size, repeat_times, soft_update_tau)
    187             buf_logprob = self.act.get_old_logprob(buf_action, buf_noise)
    188 
--> 189             buf_r_sum, buf_adv_v = self.get_reward_sum(buf_len, buf_reward, buf_mask, buf_value)  # detach()
    190             buf_adv_v = (buf_adv_v - buf_adv_v.mean()) * (self.lambda_a_value / (buf_adv_v.std() + 1e-5))
    191             # buf_adv_v: buffer data of adv_v value

/usr/local/lib/python3.7/dist-packages/elegantrl/agents/AgentPPO.py in get_reward_sum_raw(self, buf_len, buf_reward, buf_mask, buf_value)
    237         pre_r_sum = 0
    238         for i in range(buf_len - 1, -1, -1):
--> 239             buf_r_sum[i] = buf_reward[i] + buf_mask[i] * pre_r_sum
    240             pre_r_sum = buf_r_sum[i]
    241         buf_adv_v = buf_r_sum - buf_value[:, 0]

IndexError: index 8641 is out of bounds for dimension 0 with size 1

**Comment by rayrui312** [comment]
Thanks for reporting it. It is caused by ElegantRL. We are fixing it.

**Comment by rayrui312** [comment]
It is updated and should fix the issue with ElegantRL. You may have a try.

**Comment by amazingvince** [comment]
Just ran the demo. Thank you! Excited to dig in and see what yall have put together here.
