### ISSUE TITLE
Error in Demo_FinRL_Meta_Integrate_Trends_data_to_DOW_Jones.ipynb

### ISSUE THREAD

**Issue by Kartolon** [AI4Finance-Foundation/FinRL-Meta#78]
Hello,

**First issue**

if I run the jupyter notebook Demo_FinRL_Meta_Integrate_Trends_data_to_DOW_Jones.ipynb on my local computer, I receive warnings in 2 cells. In the cell 
`# !gdown --id "1sp11dtAJGGqC-3UdSn774ZD1zWCsqbn4"
!gdown --id "1m63ncE-BYlS77u5ejYTte9Nmh35DWhzp"`

I receive the warning that the command "gdown" is either written wrongly or couldnt be found. And for the cell

`!unzip "/content/Pytrends.zip"`

I get the warning

`unzip:  cannot find or open /content/Pytrends.zip, /content/Pytrends.zip.zip or /content/Pytrends.zip.ZIP.` I assume its due to these warnings that later on in the cell

`user_df = get_user_df()
len(user_df)`

I get the error `FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: 'Pytrends_Data'`

which means that "Pytrends_data" could not be found by the system. 

**Second Issue**

I tried running the code on Google Colab instead, however here I received a different error. In the cell 

`train_env_instance = get_train_env(TRAIN_START_DATE, TRAIN_END_DATE, 
                                   ticker_list, data_source, 
                                   time_interval,model_name,
                                   env,info_col)
val_env_instance = get_test_env(VAL_START_DATE, VAL_END_DATE, 
                                ticker_list, data_source,
                                time_interval, info_col, env, model_name)       `

I got the error

`<ipython-input-4-625899a50bd4> in download_data(self, ticker_list, start_date, end_date, time_interval)
     33                                           end_date = end_date,
     34                                           time_interval = time_interval)
---> 35         self.dataframe = self.processor.dataframe
     36 
     37     def clean_data(self):

AttributeError: 'YahooFinanceProcessor' object has no attribute 'dataframe'`

I would be very grateful for help for either the errors on my local computer or the error in the google colab. Thank you in advance for any help!

**Comment by zhumingpassional** [comment]
Thank you for reporting it. We will test it.

**Comment by Athe-kunal** [comment]
Hi @Kartolon 
Sorry for the delayed response. I have updated the permissions for the google drive folder, so please try again and let me know if you are able to download

**Comment by benwaldner** [comment]
> Hi @Kartolon Sorry for the delayed response. I have updated the permissions for the google drive folder, so please try again and let me know if you are able to download

On the Colab file I came across a error message (at the code block with: train_env_instance = get_train_env(TRAIN_START_DATE, TRAIN_END_DATE, ):

AttributeError                            Traceback (most recent call last)

[<ipython-input-17-184fc1e764d5>](https://localhost:8080/#) in <module>()
      2                                    ticker_list, data_source,
      3                                    time_interval,model_name,
----> 4                                    env,info_col)
      5 val_env_instance = get_test_env(VAL_START_DATE, VAL_END_DATE, 
      6                                 ticker_list, data_source,

1 frames

[<ipython-input-12-7f8b53e6053e>](https://localhost:8080/#) in get_train_env(start_date, end_date, ticker_list, data_source, time_interval, model_name, env, info_col, if_vix, **kwargs)
      5 
      6     DP = Custom_DataProcessor(data_source, **kwargs)
----> 7     DP.download_data(ticker_list, start_date, end_date, time_interval)
      8     DP.clean_data()
      9     DP.add_user_defined_features(user_df) #Adding Google trends data to our state space

[<ipython-input-4-625899a50bd4>](https://localhost:8080/#) in download_data(self, ticker_list, start_date, end_date, time_interval)
     33                                           end_date = end_date,
     34                                           time_interval = time_interval)
---> 35         self.dataframe = self.processor.dataframe
     36 
     37     def clean_data(self):

AttributeError: 'YahooFinanceProcessor' object has no attribute 'dataframe'



https://colab.research.google.com/github/AI4Finance-Foundation/FinRL-Meta/blob/master/Demo_FinRL_Meta_Integrate_Trends_data_to_DOW_Jones.ipynb#scrollTo=rtOAf118Xd0S

**Comment by benwaldner** [comment]
Update I fixed it using an older fork: https://github.com/AI4Finance-Foundation/FinRL-Meta/issues/86#issuecomment-1040298314

**Comment by Athe-kunal** [comment]
This is fixed by now, please check again
