### ISSUE TITLE
CCXTProcessor can't use BasicProcessor.add_technical_indicator or BasicProcessor.clean_data

### ISSUE THREAD

**Issue by OldFrog17** [AI4Finance-Foundation/FinRL-Meta#82]
CCXTProcessor uses a MultiIndex to organize each pairs data, but it seems that only CCXTProcessor does this while all other Processors do not. BasicProcessor.add_technical_indicator and BasicProcessor.clean_data do not handle this data format. 

Side note, it would be nice to be able to specify the exchange used by CCXTProcessor instead of forcing Binance

To reproduce:
```
from finrl.finrl_meta.data_processors.processor_ccxt import CCXTProcessor
pairs = ['BTC/USDT', 'ETH/USDT']
tech_indicator_list = [
    "macd",
    "boll_ub",
    "boll_lb",
    "rsi_30",
    "dx_30",
    "close_30_sma",
    "close_60_sma",
]
#Why do I have to specify data_source here? 
#Would be nice if we could specify exchange instead as I had to manually change mine in CCXTProcessor.
ccxtProc = CCXTProcessor('ccxt', start_date=start, end_date=end, time_interval=timeframe) 
ccxtProc.download_data(pairs)
ccxtProc.clean_data() #error here
ccxtProc.add_technical_inidicator(tech_indicator_list, 0) #error here if above skipped, neither stockstats nor talib works
```

**Comment by zhumingpassional** [comment]
Thanks for reporting it. We will test and update it.

**Comment by zhumingpassional** [comment]
Your code is not correct.

Please see test_yfinance  in https://github.com/AI4Finance-Foundation/FinRL-Meta/blob/master/finrl_meta/data_processor.py

Then you should revise your code.
