### ISSUE TITLE
Whats difference of Papertrading and Backtesting?

### ISSUE THREAD

**Issue by mryneedeffort** [AI4Finance-Foundation/FinRL-Meta#90]
![image](https://user-images.githubusercontent.com/55693668/154098870-bdbd4eb5-06ed-48cf-afc2-36b4229b64e5.png)

**Comment by jjphung** [comment]
This is the wrong place to ask a question like this. The community slack or a Google search would be a lot more helpful for you. But, I'll take a stab at answer your question. Backtesting tests your strategy using historical data. Paper trading aka forward testing tests your strategy in live market conditions with "simulated" or fake money.

**Comment by mryneedeffort** [comment]
> 
Thank you for answering my question and sorry for asking here, not next time

**Comment by XiaoYangLiu-FinRL** [comment]
It is OK. to ask any question. The team is working actively on Github.
