### ISSUE TITLE
Need to restart runtime in colab

### ISSUE THREAD

**Issue by alvaromorales1965** [AI4Finance-Foundation/FinRL-Meta#91]
Since yesterday I need to restart runtime after installing FinRL library.  Before it worked perfect.

WARNING: The following packages were previously imported in this runtime:
  [pkg_resources]
You must restart the runtime in order to use newly installed versions.

**Comment by rayrui312** [comment]
Some guess: If you don't specify the package versions in the installation part, it will probably install the newest one. So perhaps between your two times of running, some packages have been updated. You have already imported one version in the first running time. Then you installed a new version. So you need to restart runtime to use the newly installed version.

**Comment by alvaromorales1965** [comment]
Thanks
